const profile = {
  about: {
    name: "Vinicius",
    surname: "Guerrero",
    email: "vini.ts.guerrero@gmail.com",
    contact: "Senior Fullstack Software Engineer  ·  ",
    description:
      "Acting in the implementation, maintenance and development of systems, applications and database, following good programming practices. Experience in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition.",
    networks: {
      "fab fa-linkedin-in":
        "https://www.linkedin.com/in/vinicius-guerrero/",
      "fab fa-github": "https://github.com/vini-guerrero",
      "fab fa-twitter": "https://twitter.com/viniguerrero",
      "fab fa-itch-io": "https://viniguerrero.itch.io/",
      "fab fa-discord": "VinnyGuerrero#7237",
      "fab fa-youtube":
        "https://www.youtube.com/channel/UCbEKIr_SrQriVr2zNnVTHTg",
    },
  },
  interests: [
    "Self-learn system development based on .NET platform using C# programming language focusing on connected systems, object-oriented layer programming. Applications prototipes developed in WPF, MVC, Windows Forms, Views, Forms, Dashboard Alerts and Websites using HTMl5, CSS3, Javascript, JQuery, Bootstrap Framework, Bootbox.js, SignalR, NodeJS and AngularJS. Hybrid Mobile Apllication development using Ionic Framework, Cordova, Ionic, Plugins with back-end based on JSON files structure using the Firebase platform. Windows Phone 8.0 projects using XAML. Database using Stored Procedures, Triggers and Scripts. Game development, 2D using sprites or 3D FBX models, scripts, servers on Windows platform or Handheld Consoles (PSP). Additional Softwares: ​Microsoft Visual Studio .NET, SQL Server, SQL Management Studio, MySql, Access, Nero Visio, Macromedia Flash MX, Gimp, Sony Vegas, Sublime Text, Dev-C++, Notepad++, Framework XNA, Framework Windows Phone, Godot Engine, Unreal Engine, Unity, FPSC, Game Maker, Blender, Power Designer, Eclipse.",
  ],
  education: {
    "Fatec Technology University of Guarulhos": {
      subheading: "Airport Logistics",
      description:
        "Responsible for planning and controlling cargo handling and storage at an airport. Evaluates the best air transport and packaging option for each type of merchandise. Defines how loads will be loaded. It determines the organization within specific containers for air transport. Calculates freight costs and tariffs. It also analyzes airline balance sheets. Another front of activity is the passenger terminal, where the technologist works with the planning of the flow of people and luggage. In Brazil, the privatization of airports stimulated the growth and professionalization of the sector, opening the field for the technologist in Airport Logistics.",
      timeframe: "Technology - Complete",
    },
    "Cruzeiro do Sul University": {
      subheading: "Software Development",
      description:
        "Responsible for developing, designing, analyzing, implementing and maintaining information systems in different sectors. Information systems are those responsible for managing, organizing and manipulating information and data relevant to a specific sector or even an entire company. They work both in environments such as the internet and also on corporate intranet. These systems may be responsible for managing, for example, a company's inventory control data or even all information pertaining to the human resources sector database. The systems analyst is responsible for developing this software, from computer programming to integration with other machines, modeling these systems. However, the professional also needs to be based on notions of entrepreneurship, seeking to understand customers when developing systems that meet their needs. It is also important to have a certain amount of creativity to overcome possible obstacles. As the Systems Analysis and Development technologist has a strong programming base, developing games for mobile devices also presents itself as a job possibility for him.",
      timeframe: "Technology - In Progress",
    },
  },
  experiences: {
    "First Performance Global": {
      subheading: "AlphaTech Studio",
      description:
        "Solutions for digital engagement in the branch of bank transaction authorizers. Advanced financial controls, experiences for cardholders with a management panel for customers from different countries and languages, call center, mobile applications and creation of machine learning procedures.",
      timeframe: "November 2019 - Present",
    },
    "Resource IT Solutions": {
      subheading: "First Performance Global",
      description:
        "Mobile application, administrative portal and user service call center for Gogonogo project. Acting on both backend and frontend with a focus on Javascript technologies and frameworks, Node packages, ORM integrated with MySQL and PhpMyAdmin databases. White-label application architecture for several banking customers in countries such as the United States, Chile, Colombia, Brazil and Argentina, working with the reading and interpretation of bank transaction data and card control in APIs integrated with a front-end responsive. SCRUM development with Planning Poker and Requirements control via Target Process tool, daily project monitoring conferences. Customer support and log tracking.",
      timeframe: "April 2016 - November 2019",
    },
    "BRQ IT Services": {
      subheading: "Itaú Unibanco",
      description:
        "Splunk> Big Data Business Analytics project development, indexing real-time log data capture from relational or non-relational databases, XML, JSON, field extraction based on regular expressions, data analysis used to construct dashboards, views, forms, reports, alerts or graphics for events or security control measures interpretation. Project Carga Multicanal MVC System firmware upgrading solution for bank branches, providing task-schedule, filtering searches and user authentication. ActiveX component used to generate compressed packages. Windows Services and WCF agents acting in user control and SQL procedures and queries. Project Portal de Serviços MVC Web layout adaptation from a fluid-layout to a two fixed breakpoint resolution system, following browser resize changes during user navigation. Side menu change from a static dom element to a retractile JQuery UI based object.",
      timeframe: "July 2014 - January 2016",
    },
    "Benner Solution": {
      subheading: "Patrus Transportes Urgentes",
      description:
        "BL Logistics TMS / ERP System migration from Delphi architecture to .NET C# SQL table maintenance and file integration between systems. Firmware release validation, XML files reception using EDI technology, user support, data register in Supply Chain. Transport document emission (RPS /CTe). Travel, cargo and productivity report design.",
      timeframe: "March 2014 – July 2014",
    },
    "Tap Portugal": {
      subheading: "Orbital Serv. Auxiliares de Transporte Aéreo",
      description:
        "Internacional Airport Arrival Data manipulation using Worldtracer system, integrated platform to Amadeus. Customer register in PIR, AHL, DPR process, luggage customs clearance, air transport product routing and luggage tracking in national or international territory.",
      timeframe: "June 2011 – July 2012",
    },
  },
  certifications: [
    "Fluent English - Wizard Languages",
    "Big Data - Intel Corporation",
    "Spanish - Fatec Guarulhos",
    "TMS - Transport Management Systems - Benner Solution",
    "Digital Marketing Fundamentals - Universidade Anhembi Morumbi",
    "Tech Team On-Boarding - First Performance Global",
    "Developer On-Boarding - First Performance Global",
    "Tech Sales Training - First Performance Global",
    "IT Management - Next Generation Center",
    "Technology and Science - FGV",
    "People Management - FGV",
    "Conectivity Concepts - Dígitro Tecnologia",
    "C# Programming - Fundação Bradesco",
    "IT Management - Next Generation Center",
    "How to Create 3D Game Assets - Udemy",
    "Unreal Engine 4 Class- Blueprints - Udemy",
    "Game Level with Godot 3.2 and Blender 2.82 - Udemy",
    "Day-to-Day Sustainability - FGV",
    "Philosophy - FGV",
    "How to Organize the Family Budget - FGV",
    "Balanced Scorecard - FGV",
    "Software Development Process - Fundação Bradesco",
    "Windows Mobile Applications - Fundação Bradesco",
    "NETC# - Fatec Praia Grande",
    "JAVA - Curso Em Video",
    "MySQL - Curso Em Video",
    "Microsoft Word - Curso Em Video",
    "PHP - Curso Em Video",
    "HTML5 - Curso Em Video",
    "Home Office - Resource IT Solutions",
  ],
  skills: {
    icons: [
      "fab fa-apple",
      "fab fa-linux",
      "fab fa-windows",
      "fab fa-node",
      "fab fa-npm",
      "fab fa-gulp",
      "fab fa-php",
      "fab fa-python",
      "fab fa-html5",
      "fab fa-css3-alt",
      "fab fa-js-square",
      "fab fa-bootstrap",
      "fab fa-angular",
      "fab fa-react",
      "fab fa-vuejs",
      "fab fa-android",
      "fab fa-google-play",
      "fas fa-mobile-alt",
      "fab fa-app-store",
      "fab fa-wordpress",
      "fab fa-opencart",
      "fab fa-elementor",
      "fab fa-cpanel",
      "fab fa-cc-paypal",
      "fab fa-cc-stripe",
      "fas fa-database",
      "fab fa-git",
      "fab fa-github",
      "fab fa-bitbucket",
      "fab fa-jira",
      "fab fa-trello",
      "fab fa-chrome",
      "fab fa-firefox",
      "fab fa-safari",
      "fab fa-edge",
      "fab fa-docker",
      "fab fa-digital-ocean",
      "fab fa-google-drive",
      "fab fa-unity",
      "fab fa-itch-io",
    ],
    workflow: [
      "Mobile-First, Responsive Design",
      "Cross Browser Testing & Debugging",
      "Cross Functional Teams",
      "Agile Development & Scrum",
    ],
  },
  portfolio: {
    FP1: {
      url: "https://firstperformance.com/",
      img:
        "https://firstperformance.com/wp-content/uploads/2019/08/mobile-card-close-1.png",
    },
    FP2: {
      url: "https://firstperformance.com/",
      img:
        "https://firstperformance.com/wp-content/uploads/2019/09/Next-Generation-of-Card-Controls-1.png",
    },
    Avalae1: {
      url: "https://avalae.com/",
      img: "assets/portfolio/1.png",
    },
    Avalae2: {
      url: "https://avalae.com/",
      img: "assets/portfolio/2.png",
    },
    GGT: {
      url: "https://viniguerrero.itch.io/godot-game-tools",
      img: "assets/portfolio/3.png",
    },
    PRC: {
      url: "https://viniguerrero.itch.io/pre-render-creator",
      img: "assets/portfolio/4.png",
    },
  },
  portfolio_items: {
    "Godot Game Tools - GGT": [
      "With over 25k views and almost 9k downloads only on Itch.io this tool simplifies the preparation of skinned meshes animated characters 3d models by creating a fast workflow as a Python based Blender add-on that imports and exports gamedev-ready assets to include in multi-purpose projects.",
      "</br>",
      "⦿ Originally designed to Godot Engine, this tool has also been used on numerous projects over other engines such as Unity or Unreal.",
      "⦿ Batch and bake animations into a single file aiming for a significant reduction over final package as well as better file organization.",
      "⦿ Fast and easy animation manager that includes quick preview, renaming, animation trimming, keyframe reduction, animation listing and more.",
      "⦿ Support for Godot Engine Animation State Machine by generating configuration files that can be reused for as many characters as required by the project",
      "⦿ Open source project available and open to contributions on <a href='https://github.com/vini-guerrero/Godot_Game_Tools' target='_blank'>Github</a>",
      "</br>",
      "Honorable mentions as reviews and tutorials on Canadians, Americans, Brazilian and Italian Youtube Channels:",
      "<a href='https://youtu.be/utXuYpyBRN4' target='_blank'>✓ GamesfromScratch </a>",
      "<a href='https://youtu.be/EmQBLxxPV3E' target='_blank'>✓ Ombarus </a>",
      "<a href='https://youtu.be/wddbzgPouM8' target='_blank'>✓ Chili Turtle </a>",
      "<a href='https://youtu.be/REYhm82x1VA' target='_blank'>✓ Blender Lowpoly </a>",
      "<a href='https://youtu.be/UEWljYXbY3A' target='_blank'>✓ DevIsFunny </a>",
    ],
    "Pre Render Creator - PRC": [
      "Inspired by old school art style games, this tool aims to provide handy features to assist the process of turning 3D assets into 2d. Generates game ready spritesheets, bringing all the power of Blender for lighting, customized camera angles, post processing effects and more into final assets.",
      "</br>",
      "⦿ Easy, fast and customizable sprite settings such as dimensions, camera angle, rotations, effects.",
      "⦿ Provides default spritesheet presets for faster workflow. E.g. (8 Directions Sprites, 16 Directions Sprites, Custom…).",
      "⦿ Key Animation Menu, containing an animation trimmer, frames reduces and a playback for animation validation.",
      "⦿ Quick Render controls for fast prototyping in-game assets.",
      "⦿ Spritesheet tool with adjustable outputs to fit most used Game engines such as Unreal, Unity, Godot and more.",
      "</br>",
      "Available both on <a href='https://viniguerrero.itch.io/pre-render-creator' target='_blank'>Itch.io</a> as well as <a href='https://blendermarket.com/products/pre-render-creator' target='_blank'>Blender Market</a>.",
      "Showcase Project using PRC - <a href='https://youtu.be/e5c-6pBnNd0' target='_blank'>The Kindgoms Of Avalae</a>.",
    ],
    "Asset Builder": [
      "Initially designed for a requested side project, this tool provides a variety of functionalities to aid in game development. Delivers a quick and enhanced batch files handler solution for asset exchange process as well as multi-purpose generators to assist the workflow of niche requirements. Currently on version 1.0.3 but still receiving updates as a work in progress.",
      "</br>",
      "⦿ Batch import and export with individual per asset configurations and multiple file formats. E.g. (.fbx, .glb, .gltf and .obj)",
      "⦿ Customizable color palette atlas generator targets lowpoly to enhance better loading performance on textures with lightweight assets in final packages.",
      "⦿ Parameter based customizable Foliage and Rock generators for prototyping on a faster workflow with assets for level design.",
      "</br>",
      "Available on <a href='https://viniguerrero.itch.io/assetbuilder' target='_blank'>Itch.io</a>.",
    ],
  },
};
